version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
    ports:
      - "5672:5672"
      - "15672:15672"

  post:
    build:
      context: .
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//  # Используйте имя сервиса RabbitMQ
    ports:
      - "8001:8000"
    volumes:
      - ./:/app
    working_dir: /app
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
      - rabbitmq  # Добавляем зависимость от RabbitMQ

  db:
    image: postgres:alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  celery:  # Добавляем сервис для Celery
    build:
      context: .
    env_file:
      - .env
    environment:
      - CELERY_BROKER_URL=amqp://user:password@rabbitmq:5672//  # Используйте имя сервиса RabbitMQ
    volumes:
      - ./:/app
    working_dir: /app
    command: celery -A post_backend worker -l info  # Замените на ваше имя проекта
    depends_on:
      - rabbitmq
      - db

volumes:
  postgres_data:
